"""Add performance indices

Revision ID: bf38cdea9f4b
Revises: a5f38d7144d3
Create Date: 2026-07-19 03:39:46.123896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf38cdea9f4b'
down_revision: Union[str, Sequence[str], None] = 'a5f38d7144d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_doctors_specialty_id'), 'doctors', ['specialty_id'], unique=False)
    op.create_index(op.f('ix_specialties_source_id'), 'specialties', ['source_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_doctor_id'), 'subscriptions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_source_id'), 'subscriptions', ['source_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_specialty_id'), 'subscriptions', ['specialty_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_index('ix_ticket_doctor_status', 'tickets', ['doctor_id', 'status'], unique=False)
    op.create_index(op.f('ix_tickets_doctor_id'), 'tickets', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_doctor_id'), table_name='tickets')
    op.drop_index('ix_ticket_doctor_status', table_name='tickets')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_specialty_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_source_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_doctor_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_specialties_source_id'), table_name='specialties')
    op.drop_index(op.f('ix_doctors_specialty_id'), table_name='doctors')
    # ### end Alembic commands ###
